// =============================================================================
// ONBOARDING INTEGRATION
// =============================================================================
// Connects the onboarding flow to the self-composing interface.
//
// New users arrive with an empty menu (except anchors). The onboarding
// flow is their guided tour — and each step they complete gives the
// seed engine data to work with. When onboarding finishes, the seed
// engine runs for the first time, using the preferences and interests
// collected during onboarding to populate "Suggested for you."
//
// Think of onboarding as the first day at a new job. The office tour
// (onboarding steps) shows you where things are. As you visit each
// department, your mental map fills in. At the end of the day, your
// desk is arranged with the tools you'll need tomorrow — that's the
// initial seed run.
//
// Specification references:
//   Phase 6 plan — "Onboarding integration: 1–2 days —
//                    Onboarding completion triggers initial seed engine run.
//                    Onboarding steps map to first-use of tasks."
//   Phase 3 — Seed engine scoring algorithm (5 signals)
//   Phase 1 — composing-menu-store.ts (recordUse, addSeeds)
//
// Integration points:
//   - Onboarding store (existing): completion status, selected preferences
//   - seed-engine.service.ts (Phase 3): runSeedEngine
//   - composing-menu-store.ts (Phase 1): recordUse, addSeeds
//   - menu-sync.service.ts (Phase 6): saveToServer after initial population
// =============================================================================

// =============================================================================
// TYPES
// =============================================================================

/**
 * Data collected during onboarding that informs the seed engine.
 * This maps to the onboarding store's state.
 */
export interface OnboardingProfile {
  /** The user's selected role during onboarding. */
  role: string;

  /** Subject areas of interest (e.g., "Mathematics", "English", "Science"). */
  interests: string[];

  /** Year levels they work with (e.g., ["Year 1", "Year 3"]). */
  yearLevels: string[];

  /** Features they expressed interest in during onboarding. */
  selectedFeatures: string[];

  /** How they described their tech comfort level. */
  techComfort: 'beginner' | 'intermediate' | 'advanced';

  /** Whether they manage other users (teachers, students). */
  hasTeam: boolean;

  /** Whether they use the platform at an institution or independently. */
  isInstitutional: boolean;

  /** Timestamps of each onboarding step completion. */
  stepCompletions: Record<string, string>;
}

/**
 * Mapping from onboarding steps to task references.
 * When a user completes an onboarding step that involves a task,
 * we fire recordUse() to give the composing store a head start.
 */
export interface OnboardingStepMapping {
  /** The onboarding step identifier. */
  stepId: string;

  /** The task reference this step corresponds to. */
  taskRef: string;

  /** Whether completing this step should count as a "use" of the task. */
  countsAsUse: boolean;

  /**
   * Weight multiplier for seed scoring. Steps the user showed
   * particular interest in get a higher weight.
   */
  seedWeight: number;
}

/**
 * The result of processing onboarding completion.
 */
export interface OnboardingProcessResult {
  /** Whether processing completed successfully. */
  success: boolean;

  /** Number of tasks that received recordUse() from onboarding steps. */
  tasksUsed: number;

  /** Number of seeds generated by the initial seed engine run. */
  seedsGenerated: number;

  /** The task refs that were seeded. */
  seededRefs: string[];

  /** Any errors encountered during processing. */
  errors: string[];
}

// =============================================================================
// STEP MAPPINGS
// =============================================================================

/**
 * Default mappings from onboarding steps to task references.
 * These are the "this step is about that feature" connections.
 *
 * For example, if the onboarding shows the user the Gradebook during
 * a "Tour your tools" step, completing that step counts as a first
 * use of Gradebook — giving the composing store usage data before
 * the user has even started their real work.
 */
export const DEFAULT_STEP_MAPPINGS: OnboardingStepMapping[] = [
  // Teacher onboarding
  { stepId: 'tour_dashboard', taskRef: 'T0', countsAsUse: true, seedWeight: 1.0 },
  { stepId: 'tour_gradebook', taskRef: 'T3', countsAsUse: true, seedWeight: 0.8 },
  { stepId: 'tour_attendance', taskRef: 'T5', countsAsUse: true, seedWeight: 0.8 },
  { stepId: 'tour_lesson_planner', taskRef: 'T6', countsAsUse: true, seedWeight: 0.7 },
  { stepId: 'tour_assessments', taskRef: 'T8', countsAsUse: true, seedWeight: 0.7 },
  { stepId: 'tour_reports', taskRef: 'T9', countsAsUse: true, seedWeight: 0.6 },
  { stepId: 'create_first_class', taskRef: 'T2', countsAsUse: true, seedWeight: 1.0 },
  { stepId: 'invite_students', taskRef: 'T4', countsAsUse: true, seedWeight: 0.9 },

  // Parent onboarding
  { stepId: 'link_child', taskRef: 'P1', countsAsUse: true, seedWeight: 1.0 },
  { stepId: 'tour_progress', taskRef: 'P2', countsAsUse: true, seedWeight: 0.9 },
  { stepId: 'tour_messages', taskRef: 'P3', countsAsUse: true, seedWeight: 0.8 },
  { stepId: 'set_reading_goal', taskRef: 'P4', countsAsUse: true, seedWeight: 0.7 },

  // Learner onboarding
  { stepId: 'choose_avatar', taskRef: 'L0', countsAsUse: true, seedWeight: 1.0 },
  { stepId: 'first_lesson', taskRef: 'L1', countsAsUse: true, seedWeight: 1.0 },
  { stepId: 'tour_arena', taskRef: 'L3', countsAsUse: true, seedWeight: 0.8 },
  { stepId: 'tour_storybooks', taskRef: 'L4', countsAsUse: true, seedWeight: 0.9 },
  { stepId: 'earn_first_badge', taskRef: 'L5', countsAsUse: false, seedWeight: 0.6 },
];

// =============================================================================
// INTEREST-TO-TASK MAPPINGS
// =============================================================================

/**
 * Maps onboarding interest selections to task refs that should get
 * boosted seed scores. If a teacher says they're interested in
 * "Assessment & Reporting", the seed engine should prioritise
 * assessment-related tasks.
 */
export const INTEREST_TASK_BOOSTS: Record<string, string[]> = {
  // Teacher interests
  'Assessment & Reporting': ['T8', 'T9', 'T10'],
  'Lesson Planning': ['T6', 'T7'],
  'Student Management': ['T2', 'T4', 'T5'],
  'Communication': ['T11', 'T12'],
  'Content Creation': ['T13', 'T14'],
  'Analytics & Data': ['T9', 'T15'],

  // Parent interests
  'Reading Progress': ['P2', 'P4', 'P5'],
  'Homework Help': ['P6', 'P7'],
  'Teacher Communication': ['P3'],
  'Learning Activities': ['P8', 'P9'],

  // Learner interests
  'Reading': ['L1', 'L4'],
  'Games & Challenges': ['L3', 'L6'],
  'Creative Projects': ['L7', 'L8'],
  'Badges & Rewards': ['L5', 'L9'],
};

// =============================================================================
// ONBOARDING PROCESSOR
// =============================================================================

/**
 * Processes onboarding completion and bridges it to the composing interface.
 *
 * This is a stateless processor — it takes the onboarding profile and
 * the store/engine interfaces, and performs the one-time setup.
 */
export class OnboardingProcessor {
  private readonly stepMappings: OnboardingStepMapping[];

  constructor(stepMappings: OnboardingStepMapping[] = DEFAULT_STEP_MAPPINGS) {
    this.stepMappings = stepMappings;
  }

  /**
   * Process onboarding completion. Called once when the user finishes
   * the onboarding flow.
   *
   * Steps:
   * 1. Map completed onboarding steps to task uses (recordUse)
   * 2. Compute interest-based seed boosts
   * 3. Trigger the initial seed engine run
   * 4. Apply seeds to the composing store
   */
  async processOnboardingComplete(
    profile: OnboardingProfile,
    actions: {
      recordUse: (ref: string) => void;
      addSeeds: (seeds: Array<{ ref: string; score: number }>) => void;
      runSeedEngine: (
        role: string,
        context: {
          interests: string[];
          yearLevels: string[];
          techComfort: string;
          isInstitutional: boolean;
          interestBoosts: Record<string, number>;
        },
      ) => Promise<Array<{ ref: string; score: number }>>;
      saveToServer: () => Promise<void>;
    },
  ): Promise<OnboardingProcessResult> {
    const errors: string[] = [];
    let tasksUsed = 0;
    let seedsGenerated = 0;
    const seededRefs: string[] = [];

    try {
      // ── Step 1: Map onboarding steps to task uses ──

      for (const mapping of this.stepMappings) {
        if (!mapping.countsAsUse) continue;

        // Check if this step was completed during onboarding
        if (profile.stepCompletions[mapping.stepId]) {
          try {
            actions.recordUse(mapping.taskRef);
            tasksUsed++;
          } catch (err) {
            errors.push(
              `Failed to record use for ${mapping.taskRef}: ${
                err instanceof Error ? err.message : 'Unknown error'
              }`,
            );
          }
        }
      }

      // ── Step 2: Compute interest-based boosts ──

      const interestBoosts: Record<string, number> = {};

      for (const interest of profile.interests) {
        const boostedTasks = INTEREST_TASK_BOOSTS[interest];
        if (!boostedTasks) continue;

        for (const taskRef of boostedTasks) {
          interestBoosts[taskRef] = (interestBoosts[taskRef] ?? 0) + 0.15;
        }
      }

      // Also boost tasks from completed onboarding steps
      for (const mapping of this.stepMappings) {
        if (profile.stepCompletions[mapping.stepId]) {
          interestBoosts[mapping.taskRef] =
            (interestBoosts[mapping.taskRef] ?? 0) + (mapping.seedWeight * 0.1);
        }
      }

      // ── Step 3: Trigger initial seed engine run ──

      try {
        const seeds = await actions.runSeedEngine(profile.role, {
          interests: profile.interests,
          yearLevels: profile.yearLevels,
          techComfort: profile.techComfort,
          isInstitutional: profile.isInstitutional,
          interestBoosts,
        });

        seedsGenerated = seeds.length;
        seededRefs.push(...seeds.map(s => s.ref));

        // ── Step 4: Apply seeds to the composing store ──

        if (seeds.length > 0) {
          actions.addSeeds(seeds);
        }
      } catch (err) {
        errors.push(
          `Seed engine failed: ${err instanceof Error ? err.message : 'Unknown error'}`,
        );
      }

      // ── Step 5: Save to server ──

      try {
        await actions.saveToServer();
      } catch (err) {
        // Non-fatal — local state is correct, will sync later
        errors.push(
          `Server save failed (will retry): ${
            err instanceof Error ? err.message : 'Unknown error'
          }`,
        );
      }

      return {
        success: errors.length === 0,
        tasksUsed,
        seedsGenerated,
        seededRefs,
        errors,
      };
    } catch (err) {
      return {
        success: false,
        tasksUsed,
        seedsGenerated,
        seededRefs,
        errors: [
          ...errors,
          `Onboarding processing failed: ${
            err instanceof Error ? err.message : 'Unknown error'
          }`,
        ],
      };
    }
  }

  /**
   * Get the tasks that should be pre-activated based on the user's role
   * and tech comfort level. These aren't seeds — they're items that
   * start in the ACTIVE state immediately, giving the user a working
   * menu from day one.
   *
   * A beginner teacher gets fewer items (less overwhelming).
   * An advanced teacher gets more items (they can handle the density).
   */
  getInitialActiveItems(
    role: string,
    techComfort: 'beginner' | 'intermediate' | 'advanced',
  ): string[] {
    const roleDefaults: Record<string, Record<string, string[]>> = {
      teacher: {
        beginner: ['T0', 'T2'],               // Dashboard, Classes
        intermediate: ['T0', 'T2', 'T3'],     // + Gradebook
        advanced: ['T0', 'T2', 'T3', 'T5'],   // + Attendance
      },
      parent: {
        beginner: ['P0', 'P1'],                // Dashboard, Children
        intermediate: ['P0', 'P1', 'P2'],     // + Progress
        advanced: ['P0', 'P1', 'P2', 'P3'],   // + Messages
      },
      learner: {
        beginner: ['L0'],                      // Home only
        intermediate: ['L0', 'L1'],            // + Learn
        advanced: ['L0', 'L1', 'L3'],          // + Arena
      },
      tutor: {
        beginner: ['TU0', 'TU1'],              // Dashboard, Sessions
        intermediate: ['TU0', 'TU1', 'TU2'],  // + Students
        advanced: ['TU0', 'TU1', 'TU2', 'TU3'], // + Earnings
      },
      admin: {
        beginner: ['A0', 'A1'],                // Dashboard, Users
        intermediate: ['A0', 'A1', 'A2'],     // + Reports
        advanced: ['A0', 'A1', 'A2', 'A3'],   // + Settings
      },
    };

    return roleDefaults[role]?.[techComfort] ?? roleDefaults[role]?.['beginner'] ?? [];
  }

  /**
   * Determine which step mappings apply to a given role.
   */
  getMappingsForRole(role: string): OnboardingStepMapping[] {
    const rolePrefixes: Record<string, string[]> = {
      teacher: ['tour_', 'create_', 'invite_'],
      parent: ['link_', 'tour_progress', 'tour_messages', 'set_'],
      learner: ['choose_', 'first_', 'tour_arena', 'tour_storybooks', 'earn_'],
      tutor: ['tour_'],
      admin: ['tour_'],
    };

    const prefixes = rolePrefixes[role] ?? [];
    return this.stepMappings.filter(
      m => prefixes.some(p => m.stepId.startsWith(p)),
    );
  }
}
