// ============================================================================
// SCHOLARLY PLATFORM — Sprint 20, Deliverable S20-001
// S3 + CloudFront + Secrets Management
// ============================================================================
//
// Sprint 19 provisioned the database and cache — the warehouse where data
// lives. This sprint provisions the content delivery layer — the fleet of
// trucks that carries storybook illustrations, audio narration, and book
// manifests from the warehouse to every child's device, fast.
//
// Three components:
//   1. S3 Bucket Configuration: where content is stored, with lifecycle
//      policies, versioning, and CORS for direct browser uploads
//   2. CloudFront Distribution: the CDN edge network that caches content
//      at 400+ locations worldwide, ensuring a child in rural Australia
//      gets their storybook illustrations as fast as one in Sydney
//   3. Secrets Management: centralised, encrypted storage for all API keys
//      (Claude, ElevenLabs, GPT Image) with automatic rotation
//
// The critical integration: Sprint 18's FileStorageService (S18-003)
// defined the interface — StorageConfig, upload(), getPresignedUploadUrl().
// This sprint provisions the actual S3 bucket and CloudFront distribution
// that make those methods work against real AWS infrastructure.
// ============================================================================

import { ScholarlyBaseService, Result, ok, fail } from '../shared/base';

// ==========================================================================
// Section 1: S3 Bucket Configuration
// ==========================================================================
// The S3 bucket is the canonical store for all storybook content. Every
// illustration generated by the illustration pipeline (S20-002), every
// audio narration from ElevenLabs (Sprint 21), and every book manifest
// passes through this bucket. The path hierarchy mirrors Sprint 18's
// StoragePath type:
//   tenants/{tenantId}/storybooks/{bookId}/illustrations/page-{n}.webp
//   tenants/{tenantId}/storybooks/{bookId}/audio/page-{n}.mp3
//   tenants/{tenantId}/storybooks/{bookId}/manifest.json
//   tenants/{tenantId}/characters/{charId}/style-sheet.png
//   seed-library/{bookId}/{asset}

export interface S3BucketConfig {
  readonly bucketName: string;
  readonly region: string;
  readonly environment: string;
  readonly enableVersioning: boolean;
  readonly enableEncryption: boolean;
  readonly encryptionKeyArn?: string;        // KMS key for SSE-KMS
  readonly corsAllowedOrigins: string[];     // For direct browser uploads
  readonly lifecyclePolicies: LifecyclePolicy[];
  readonly replicationConfig?: ReplicationConfig;
  readonly accessLogging: AccessLoggingConfig;
  readonly intelligentTiering: boolean;      // Auto-move to cheaper storage
  readonly blockPublicAccess: boolean;       // Always true — CloudFront serves
}

export interface LifecyclePolicy {
  readonly id: string;
  readonly prefix: string;                   // e.g. 'tenants/' or 'seed-library/'
  readonly transitions: StorageTransition[];
  readonly expirationDays?: number;          // Delete after N days (for temp uploads)
  readonly abortIncompleteMultipartDays: number;
}

export interface StorageTransition {
  readonly days: number;
  readonly storageClass: 'STANDARD_IA' | 'GLACIER_IR' | 'GLACIER' | 'DEEP_ARCHIVE';
}

export interface ReplicationConfig {
  readonly destinationBucket: string;
  readonly destinationRegion: string;        // Cross-region for disaster recovery
  readonly replicateEncryption: boolean;
}

export interface AccessLoggingConfig {
  readonly enabled: boolean;
  readonly targetBucket: string;
  readonly targetPrefix: string;
}

/**
 * Environment-specific S3 configurations.
 *
 * Key design decisions:
 * - Versioning enabled everywhere: protects against accidental deletion
 *   and enables rollback of content updates
 * - Block public access: ALL content served via CloudFront OAI, never
 *   directly from S3. This prevents URL guessing attacks.
 * - Intelligent tiering: illustrations accessed frequently in the first
 *   month after generation, then drop to Standard-IA automatically
 * - Lifecycle policies: temporary upload staging area cleaned after 24h,
 *   deleted storybooks move to Glacier after 90 days (GDPR retention)
 */
export const S3_CONFIGS: Record<string, S3BucketConfig> = {
  development: {
    bucketName: 'scholarly-content-dev',
    region: 'ap-southeast-2',
    environment: 'development',
    enableVersioning: true,
    enableEncryption: true,
    corsAllowedOrigins: ['http://localhost:3000', 'http://localhost:8081'],
    lifecyclePolicies: [
      {
        id: 'temp-cleanup', prefix: 'temp/',
        transitions: [], expirationDays: 1, abortIncompleteMultipartDays: 1,
      },
      {
        id: 'content-tiering', prefix: 'tenants/',
        transitions: [{ days: 30, storageClass: 'STANDARD_IA' }],
        abortIncompleteMultipartDays: 7,
      },
    ],
    accessLogging: { enabled: false, targetBucket: '', targetPrefix: '' },
    intelligentTiering: false,
    blockPublicAccess: true,
  },
  staging: {
    bucketName: 'scholarly-content-staging',
    region: 'ap-southeast-2',
    environment: 'staging',
    enableVersioning: true,
    enableEncryption: true,
    corsAllowedOrigins: ['https://staging.scholarly.app'],
    lifecyclePolicies: [
      {
        id: 'temp-cleanup', prefix: 'temp/',
        transitions: [], expirationDays: 1, abortIncompleteMultipartDays: 1,
      },
      {
        id: 'content-tiering', prefix: 'tenants/',
        transitions: [
          { days: 30, storageClass: 'STANDARD_IA' },
          { days: 90, storageClass: 'GLACIER_IR' },
        ],
        abortIncompleteMultipartDays: 7,
      },
    ],
    accessLogging: { enabled: true, targetBucket: 'scholarly-logs-staging', targetPrefix: 's3-access/' },
    intelligentTiering: true,
    blockPublicAccess: true,
  },
  production: {
    bucketName: 'scholarly-content-prod',
    region: 'ap-southeast-2',
    environment: 'production',
    enableVersioning: true,
    enableEncryption: true,
    encryptionKeyArn: 'arn:aws:kms:ap-southeast-2:ACCOUNT:key/KEY_ID',
    corsAllowedOrigins: ['https://scholarly.app', 'https://www.scholarly.app'],
    lifecyclePolicies: [
      {
        id: 'temp-cleanup', prefix: 'temp/',
        transitions: [], expirationDays: 1, abortIncompleteMultipartDays: 1,
      },
      {
        id: 'content-tiering', prefix: 'tenants/',
        transitions: [
          { days: 60, storageClass: 'STANDARD_IA' },
          { days: 180, storageClass: 'GLACIER_IR' },
        ],
        abortIncompleteMultipartDays: 7,
      },
      {
        id: 'deleted-content-retention', prefix: 'deleted/',
        transitions: [
          { days: 30, storageClass: 'GLACIER' },
        ],
        expirationDays: 365,    // GDPR: delete after 1 year
        abortIncompleteMultipartDays: 1,
      },
    ],
    replicationConfig: {
      destinationBucket: 'scholarly-content-prod-replica',
      destinationRegion: 'ap-southeast-1',  // Singapore — DR region
      replicateEncryption: true,
    },
    accessLogging: { enabled: true, targetBucket: 'scholarly-logs-prod', targetPrefix: 's3-access/' },
    intelligentTiering: true,
    blockPublicAccess: true,
  },
};

// ==========================================================================
// Section 2: CloudFront Distribution Configuration
// ==========================================================================
// CloudFront is the CDN that sits between S3 and the user's device. When
// a child opens a storybook, their browser doesn't fetch illustrations
// from the S3 bucket in Sydney — it fetches from the nearest CloudFront
// edge location (which might be Perth, Melbourne, or Singapore). After
// the first request, CloudFront caches the content at the edge for
// subsequent readers.
//
// The Origin Access Identity (OAI) is a security mechanism: only
// CloudFront can read from the S3 bucket. Direct S3 URLs don't work.
// This prevents content leakage and ensures all access is logged,
// metered, and cacheable.

export interface CloudFrontConfig {
  readonly distributionName: string;
  readonly environment: string;
  readonly originBucket: string;
  readonly originRegion: string;
  readonly aliases: string[];               // Custom domain names
  readonly certificateArn?: string;          // ACM cert for HTTPS on custom domain
  readonly priceClass: 'PriceClass_100' | 'PriceClass_200' | 'PriceClass_All';
  readonly defaultTtlSeconds: number;
  readonly maxTtlSeconds: number;
  readonly minTtlSeconds: number;
  readonly cachePolicies: CachePolicyConfig[];
  readonly geoRestrictions: GeoRestrictionConfig;
  readonly wafWebAclArn?: string;            // Web Application Firewall
  readonly enableAccessLogs: boolean;
  readonly logBucket: string;
  readonly responseHeaders: ResponseHeadersConfig;
  readonly errorPages: ErrorPageConfig[];
  readonly enableCompression: boolean;
  readonly enableHttp2: boolean;
  readonly enableHttp3: boolean;
}

export interface CachePolicyConfig {
  readonly pathPattern: string;             // e.g. '/tenants/*/illustrations/*'
  readonly ttlSeconds: number;
  readonly compress: boolean;
  readonly allowedMethods: ('GET' | 'HEAD' | 'OPTIONS' | 'PUT' | 'POST')[];
  readonly cachedMethods: ('GET' | 'HEAD')[];
  readonly forwardHeaders: string[];        // Headers to include in cache key
  readonly forwardQueryStrings: boolean;
}

export interface GeoRestrictionConfig {
  readonly type: 'none' | 'whitelist' | 'blacklist';
  readonly countries: string[];             // ISO 3166-1 alpha-2 codes
}

export interface ResponseHeadersConfig {
  readonly securityHeaders: boolean;        // Strict-Transport-Security, X-Content-Type-Options
  readonly corsHeaders: boolean;
  readonly customHeaders: Record<string, string>;
}

export interface ErrorPageConfig {
  readonly errorCode: number;
  readonly responseCode: number;
  readonly responsePagePath: string;
  readonly cacheTtlSeconds: number;
}

/**
 * CloudFront configurations per environment.
 *
 * Cache strategy for children's storybook content:
 * - Illustrations (immutable, content-addressed): 1 year TTL
 *   Once generated, an illustration never changes — its URL includes
 *   a content hash. This is the same pattern used by Webpack's
 *   [contenthash] for static assets.
 *
 * - Audio narration (immutable): 1 year TTL
 *   Same rationale as illustrations.
 *
 * - Book manifests (mutable): 1 hour TTL
 *   Manifests may be updated when a book is revised or when new
 *   metadata is added. Short TTL ensures children see updates quickly.
 *
 * - Character style sheets: 24 hour TTL
 *   Updated infrequently, when an illustrator refines a character design.
 *
 * Price class decisions:
 * - Dev: PriceClass_100 (cheapest — US, Europe, Japan, Israel only)
 * - Staging: PriceClass_200 (adds Asia-Pacific — covers Australia)
 * - Production: PriceClass_All (global coverage for international schools)
 */
export const CLOUDFRONT_CONFIGS: Record<string, CloudFrontConfig> = {
  development: {
    distributionName: 'scholarly-cdn-dev',
    environment: 'development',
    originBucket: 'scholarly-content-dev',
    originRegion: 'ap-southeast-2',
    aliases: [],
    priceClass: 'PriceClass_100',
    defaultTtlSeconds: 3600,
    maxTtlSeconds: 86400,
    minTtlSeconds: 0,
    cachePolicies: [
      {
        pathPattern: '*/illustrations/*',
        ttlSeconds: 31536000,  // 1 year
        compress: true, allowedMethods: ['GET', 'HEAD'],
        cachedMethods: ['GET', 'HEAD'], forwardHeaders: [], forwardQueryStrings: false,
      },
      {
        pathPattern: '*/audio/*',
        ttlSeconds: 31536000,
        compress: false,  // Audio already compressed
        allowedMethods: ['GET', 'HEAD'],
        cachedMethods: ['GET', 'HEAD'], forwardHeaders: [], forwardQueryStrings: false,
      },
      {
        pathPattern: '*/manifest.json',
        ttlSeconds: 3600,  // 1 hour
        compress: true, allowedMethods: ['GET', 'HEAD'],
        cachedMethods: ['GET', 'HEAD'], forwardHeaders: [], forwardQueryStrings: false,
      },
    ],
    geoRestrictions: { type: 'none', countries: [] },
    enableAccessLogs: false,
    logBucket: '',
    responseHeaders: { securityHeaders: true, corsHeaders: true, customHeaders: {} },
    errorPages: [
      { errorCode: 403, responseCode: 404, responsePagePath: '/error/404.html', cacheTtlSeconds: 300 },
      { errorCode: 404, responseCode: 404, responsePagePath: '/error/404.html', cacheTtlSeconds: 300 },
    ],
    enableCompression: true,
    enableHttp2: true,
    enableHttp3: false,
  },
  staging: {
    distributionName: 'scholarly-cdn-staging',
    environment: 'staging',
    originBucket: 'scholarly-content-staging',
    originRegion: 'ap-southeast-2',
    aliases: ['cdn-staging.scholarly.app'],
    certificateArn: 'arn:aws:acm:us-east-1:ACCOUNT:certificate/CERT_ID',
    priceClass: 'PriceClass_200',
    defaultTtlSeconds: 3600,
    maxTtlSeconds: 86400,
    minTtlSeconds: 0,
    cachePolicies: [
      { pathPattern: '*/illustrations/*', ttlSeconds: 31536000, compress: true,
        allowedMethods: ['GET', 'HEAD'], cachedMethods: ['GET', 'HEAD'],
        forwardHeaders: [], forwardQueryStrings: false },
      { pathPattern: '*/audio/*', ttlSeconds: 31536000, compress: false,
        allowedMethods: ['GET', 'HEAD'], cachedMethods: ['GET', 'HEAD'],
        forwardHeaders: [], forwardQueryStrings: false },
      { pathPattern: '*/manifest.json', ttlSeconds: 3600, compress: true,
        allowedMethods: ['GET', 'HEAD'], cachedMethods: ['GET', 'HEAD'],
        forwardHeaders: [], forwardQueryStrings: false },
    ],
    geoRestrictions: { type: 'none', countries: [] },
    enableAccessLogs: true,
    logBucket: 'scholarly-logs-staging',
    responseHeaders: { securityHeaders: true, corsHeaders: true, customHeaders: {} },
    errorPages: [
      { errorCode: 403, responseCode: 404, responsePagePath: '/error/404.html', cacheTtlSeconds: 300 },
      { errorCode: 404, responseCode: 404, responsePagePath: '/error/404.html', cacheTtlSeconds: 300 },
    ],
    enableCompression: true,
    enableHttp2: true,
    enableHttp3: true,
  },
  production: {
    distributionName: 'scholarly-cdn-prod',
    environment: 'production',
    originBucket: 'scholarly-content-prod',
    originRegion: 'ap-southeast-2',
    aliases: ['cdn.scholarly.app'],
    certificateArn: 'arn:aws:acm:us-east-1:ACCOUNT:certificate/PROD_CERT_ID',
    priceClass: 'PriceClass_All',
    defaultTtlSeconds: 3600,
    maxTtlSeconds: 31536000,
    minTtlSeconds: 0,
    cachePolicies: [
      { pathPattern: '*/illustrations/*', ttlSeconds: 31536000, compress: true,
        allowedMethods: ['GET', 'HEAD'], cachedMethods: ['GET', 'HEAD'],
        forwardHeaders: [], forwardQueryStrings: false },
      { pathPattern: '*/audio/*', ttlSeconds: 31536000, compress: false,
        allowedMethods: ['GET', 'HEAD'], cachedMethods: ['GET', 'HEAD'],
        forwardHeaders: [], forwardQueryStrings: false },
      { pathPattern: '*/manifest.json', ttlSeconds: 3600, compress: true,
        allowedMethods: ['GET', 'HEAD'], cachedMethods: ['GET', 'HEAD'],
        forwardHeaders: [], forwardQueryStrings: false },
      { pathPattern: '*/characters/*', ttlSeconds: 86400, compress: true,
        allowedMethods: ['GET', 'HEAD'], cachedMethods: ['GET', 'HEAD'],
        forwardHeaders: [], forwardQueryStrings: false },
    ],
    geoRestrictions: { type: 'none', countries: [] },
    wafWebAclArn: 'arn:aws:wafv2:us-east-1:ACCOUNT:global/webacl/scholarly-cdn-waf/ID',
    enableAccessLogs: true,
    logBucket: 'scholarly-logs-prod',
    responseHeaders: {
      securityHeaders: true,
      corsHeaders: true,
      customHeaders: {
        'X-Scholarly-Environment': 'production',
        'X-Content-Type-Options': 'nosniff',
        'X-Frame-Options': 'DENY',
        'Referrer-Policy': 'strict-origin-when-cross-origin',
      },
    },
    errorPages: [
      { errorCode: 403, responseCode: 404, responsePagePath: '/error/404.html', cacheTtlSeconds: 300 },
      { errorCode: 404, responseCode: 404, responsePagePath: '/error/404.html', cacheTtlSeconds: 300 },
      { errorCode: 500, responseCode: 500, responsePagePath: '/error/500.html', cacheTtlSeconds: 60 },
      { errorCode: 502, responseCode: 502, responsePagePath: '/error/502.html', cacheTtlSeconds: 10 },
    ],
    enableCompression: true,
    enableHttp2: true,
    enableHttp3: true,
  },
};

// ==========================================================================
// Section 3: Secrets Management Configuration
// ==========================================================================
// All API keys and sensitive credentials live in AWS Secrets Manager.
// Sprint 19 already created secrets for database credentials and Redis
// auth tokens. This sprint adds secrets for the three AI providers that
// the Storybook Engine depends on:
//   - Anthropic Claude: narrative generation (Sprint 19 S19-002)
//   - OpenAI GPT Image: illustration generation (Sprint 20 S20-002)
//   - ElevenLabs: audio narration (Sprint 21)
//
// Secrets are never in environment variables, config files, or source
// code. The application reads them at startup via the IAM role that
// Sprint 19 provisioned. Automatic rotation ensures keys are refreshed
// without downtime.

export interface SecretConfig {
  readonly name: string;
  readonly description: string;
  readonly provider: string;
  readonly rotationEnabled: boolean;
  readonly rotationDays: number;
  readonly tags: Record<string, string>;
  readonly fields: SecretField[];
}

export interface SecretField {
  readonly key: string;
  readonly description: string;
  readonly sensitive: boolean;
  readonly rotatable: boolean;
}

export const SECRETS_CONFIGS: SecretConfig[] = [
  {
    name: 'scholarly-anthropic-api',
    description: 'Anthropic Claude API credentials for narrative generation',
    provider: 'anthropic',
    rotationEnabled: true,
    rotationDays: 90,
    tags: { Service: 'storybook-engine', Component: 'narrative-generator' },
    fields: [
      { key: 'api_key', description: 'Anthropic API key', sensitive: true, rotatable: true },
      { key: 'model_id', description: 'Default model identifier', sensitive: false, rotatable: false },
      { key: 'max_tokens_per_request', description: 'Token budget per request', sensitive: false, rotatable: false },
      { key: 'monthly_budget_usd', description: 'Monthly spend limit', sensitive: false, rotatable: false },
    ],
  },
  {
    name: 'scholarly-openai-api',
    description: 'OpenAI API credentials for illustration generation (GPT Image)',
    provider: 'openai',
    rotationEnabled: true,
    rotationDays: 90,
    tags: { Service: 'storybook-engine', Component: 'illustration-pipeline' },
    fields: [
      { key: 'api_key', description: 'OpenAI API key', sensitive: true, rotatable: true },
      { key: 'organization_id', description: 'OpenAI organization ID', sensitive: false, rotatable: false },
      { key: 'image_model', description: 'Image generation model (gpt-image-1)', sensitive: false, rotatable: false },
      { key: 'monthly_budget_usd', description: 'Monthly spend limit', sensitive: false, rotatable: false },
    ],
  },
  {
    name: 'scholarly-elevenlabs-api',
    description: 'ElevenLabs API credentials for audio narration',
    provider: 'elevenlabs',
    rotationEnabled: true,
    rotationDays: 90,
    tags: { Service: 'storybook-engine', Component: 'audio-narration' },
    fields: [
      { key: 'api_key', description: 'ElevenLabs API key', sensitive: true, rotatable: true },
      { key: 'default_voice_id', description: 'Default narrator voice', sensitive: false, rotatable: false },
      { key: 'monthly_character_limit', description: 'Character budget per month', sensitive: false, rotatable: false },
    ],
  },
];

// ==========================================================================
// Section 4: Terraform Generator for Storage Infrastructure
// ==========================================================================

export class StorageTerraformGenerator extends ScholarlyBaseService {
  constructor() {
    super('StorageTerraformGenerator');
  }

  /**
   * Generate Terraform HCL for S3 + CloudFront + Secrets Manager.
   * Produces 4 files that extend Sprint 19's module suite.
   */
  generate(
    s3Config: S3BucketConfig,
    cfConfig: CloudFrontConfig,
    secrets: SecretConfig[],
  ): Result<Map<string, string>> {
    try {
      const files = new Map<string, string>();
      files.set('s3.tf', this.generateS3(s3Config));
      files.set('cloudfront.tf', this.generateCloudFront(cfConfig, s3Config));
      files.set('secrets-api-keys.tf', this.generateSecrets(secrets, s3Config.environment));
      files.set('storage-outputs.tf', this.generateOutputs(s3Config, cfConfig));

      this.log('info', `Generated ${files.size} storage Terraform files`, {
        environment: s3Config.environment,
        bucket: s3Config.bucketName,
        distribution: cfConfig.distributionName,
        secrets: secrets.length,
      });

      return ok(files);
    } catch (error) {
      return fail(`Storage Terraform generation failed: ${error}`);
    }
  }

  private generateS3(config: S3BucketConfig): string {
    const lifecycleRules = config.lifecyclePolicies.map(policy => {
      const transitions = policy.transitions.map(t =>
        `    transition {
      days          = ${t.days}
      storage_class = "${t.storageClass}"
    }`).join('\n');

      return `
  rule {
    id      = "${policy.id}"
    status  = "Enabled"
    prefix  = "${policy.prefix}"
${transitions}
    ${policy.expirationDays ? `expiration { days = ${policy.expirationDays} }` : ''}
    abort_incomplete_multipart_upload { days_after_initiation = ${policy.abortIncompleteMultipartDays} }
  }`;
    }).join('\n');

    const corsRules = config.corsAllowedOrigins.length > 0 ? `
resource "aws_s3_bucket_cors_configuration" "content" {
  bucket = aws_s3_bucket.content.id

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["GET", "PUT", "POST", "HEAD"]
    allowed_origins = [${config.corsAllowedOrigins.map(o => `"${o}"`).join(', ')}]
    expose_headers  = ["ETag", "x-amz-request-id"]
    max_age_seconds = 3600
  }
}` : '';

    const replication = config.replicationConfig ? `
resource "aws_s3_bucket_replication_configuration" "content" {
  bucket = aws_s3_bucket.content.id
  role   = aws_iam_role.s3_replication.arn

  rule {
    id     = "cross-region-replication"
    status = "Enabled"

    destination {
      bucket        = "arn:aws:s3:::${config.replicationConfig.destinationBucket}"
      storage_class = "STANDARD_IA"
    }
  }
}

resource "aws_iam_role" "s3_replication" {
  name = "scholarly-${config.environment}-s3-replication"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{ Action = "sts:AssumeRole", Effect = "Allow",
      Principal = { Service = "s3.amazonaws.com" } }]
  })
}` : '';

    return `# ============================================================
# S3 Content Bucket — ${config.environment}
# ============================================================
# Stores all storybook assets: illustrations, audio, manifests,
# character style sheets, and marketplace content.
# Access: CloudFront OAI only (no direct public access).
# ============================================================

resource "aws_s3_bucket" "content" {
  bucket = "${config.bucketName}"

  tags = {
    Name        = "${config.bucketName}"
    Environment = "${config.environment}"
    Service     = "storybook-engine"
  }
}

resource "aws_s3_bucket_versioning" "content" {
  bucket = aws_s3_bucket.content.id
  versioning_configuration {
    status = "${config.enableVersioning ? 'Enabled' : 'Suspended'}"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "content" {
  bucket = aws_s3_bucket.content.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = "${config.encryptionKeyArn ? 'aws:kms' : 'AES256'}"
      ${config.encryptionKeyArn ? `kms_master_key_id = "${config.encryptionKeyArn}"` : ''}
    }
    bucket_key_enabled = true
  }
}

resource "aws_s3_bucket_public_access_block" "content" {
  bucket = aws_s3_bucket.content.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_lifecycle_configuration" "content" {
  bucket = aws_s3_bucket.content.id
${lifecycleRules}
}

${config.intelligentTiering ? `
resource "aws_s3_bucket_intelligent_tiering_configuration" "content" {
  bucket = aws_s3_bucket.content.id
  name   = "storybook-tiering"

  tiering {
    access_tier = "ARCHIVE_ACCESS"
    days        = 90
  }
  tiering {
    access_tier = "DEEP_ARCHIVE_ACCESS"
    days        = 180
  }
}` : ''}

${corsRules}

${config.accessLogging.enabled ? `
resource "aws_s3_bucket_logging" "content" {
  bucket        = aws_s3_bucket.content.id
  target_bucket = "${config.accessLogging.targetBucket}"
  target_prefix = "${config.accessLogging.targetPrefix}"
}` : ''}

# Bucket policy: allow CloudFront OAI read access only
resource "aws_s3_bucket_policy" "content" {
  bucket = aws_s3_bucket.content.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "AllowCloudFrontOAI"
        Effect    = "Allow"
        Principal = { AWS = aws_cloudfront_origin_access_identity.content.iam_arn }
        Action    = "s3:GetObject"
        Resource  = "\${aws_s3_bucket.content.arn}/*"
      },
      {
        Sid       = "AllowAppRoleWrite"
        Effect    = "Allow"
        Principal = { AWS = aws_iam_role.application.arn }
        Action    = ["s3:PutObject", "s3:GetObject", "s3:DeleteObject", "s3:ListBucket"]
        Resource  = [
          aws_s3_bucket.content.arn,
          "\${aws_s3_bucket.content.arn}/*"
        ]
      }
    ]
  })
}

${replication}
`;
  }

  private generateCloudFront(cfConfig: CloudFrontConfig, s3Config: S3BucketConfig): string {
    const cacheBehaviours = cfConfig.cachePolicies.map(policy => `
  ordered_cache_behavior {
    path_pattern     = "${policy.pathPattern}"
    allowed_methods  = [${policy.allowedMethods.map(m => `"${m}"`).join(', ')}]
    cached_methods   = [${policy.cachedMethods.map(m => `"${m}"`).join(', ')}]
    target_origin_id = local.s3_origin_id
    compress         = ${policy.compress}

    forwarded_values {
      query_string = ${policy.forwardQueryStrings}
      cookies { forward = "none" }
    }

    viewer_protocol_policy = "redirect-to-https"
    min_ttl                = 0
    default_ttl            = ${policy.ttlSeconds}
    max_ttl                = ${policy.ttlSeconds}
  }`).join('\n');

    const errorResponses = cfConfig.errorPages.map(ep => `
  custom_error_response {
    error_code            = ${ep.errorCode}
    response_code         = ${ep.responseCode}
    response_page_path    = "${ep.responsePagePath}"
    error_caching_min_ttl = ${ep.cacheTtlSeconds}
  }`).join('\n');

    return `# ============================================================
# CloudFront Distribution — ${cfConfig.environment}
# ============================================================
# CDN for storybook content delivery. All S3 access goes through
# CloudFront via Origin Access Identity (no direct S3 URLs).
# Cache TTLs: illustrations/audio 1yr, manifests 1hr.
# ============================================================

locals {
  s3_origin_id = "S3-${s3Config.bucketName}"
}

resource "aws_cloudfront_origin_access_identity" "content" {
  comment = "OAI for ${s3Config.bucketName}"
}

resource "aws_cloudfront_distribution" "content" {
  origin {
    domain_name = aws_s3_bucket.content.bucket_regional_domain_name
    origin_id   = local.s3_origin_id

    s3_origin_config {
      origin_access_identity = aws_cloudfront_origin_access_identity.content.cloudfront_access_identity_path
    }
  }

  enabled             = true
  is_ipv6_enabled     = true
  http_version        = "${cfConfig.enableHttp3 ? 'http3' : cfConfig.enableHttp2 ? 'http2' : 'http1.1'}"
  price_class         = "${cfConfig.priceClass}"
  comment             = "Scholarly ${cfConfig.environment} content CDN"
  default_root_object = ""
  ${cfConfig.aliases.length > 0 ? `aliases = [${cfConfig.aliases.map(a => `"${a}"`).join(', ')}]` : ''}
  ${cfConfig.wafWebAclArn ? `web_acl_id = "${cfConfig.wafWebAclArn}"` : ''}

  default_cache_behavior {
    allowed_methods  = ["GET", "HEAD", "OPTIONS"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = local.s3_origin_id
    compress         = ${cfConfig.enableCompression}

    forwarded_values {
      query_string = false
      cookies { forward = "none" }
    }

    viewer_protocol_policy = "redirect-to-https"
    min_ttl                = ${cfConfig.minTtlSeconds}
    default_ttl            = ${cfConfig.defaultTtlSeconds}
    max_ttl                = ${cfConfig.maxTtlSeconds}
  }

${cacheBehaviours}

${errorResponses}

  restrictions {
    geo_restriction {
      restriction_type = "${cfConfig.geoRestrictions.type}"
      ${cfConfig.geoRestrictions.countries.length > 0
        ? `locations = [${cfConfig.geoRestrictions.countries.map(c => `"${c}"`).join(', ')}]`
        : ''}
    }
  }

  viewer_certificate {
    ${cfConfig.certificateArn
      ? `acm_certificate_arn      = "${cfConfig.certificateArn}"
    ssl_support_method       = "sni-only"
    minimum_protocol_version = "TLSv1.2_2021"`
      : 'cloudfront_default_certificate = true'}
  }

  ${cfConfig.enableAccessLogs ? `
  logging_config {
    include_cookies = false
    bucket          = "${cfConfig.logBucket}.s3.amazonaws.com"
    prefix          = "cloudfront/"
  }` : ''}

  ${cfConfig.responseHeaders.securityHeaders ? `
  # Response headers policy
  response_headers_policy_id = aws_cloudfront_response_headers_policy.security.id` : ''}

  tags = {
    Name        = "${cfConfig.distributionName}"
    Environment = "${cfConfig.environment}"
  }
}

${cfConfig.responseHeaders.securityHeaders ? `
resource "aws_cloudfront_response_headers_policy" "security" {
  name = "scholarly-${cfConfig.environment}-security-headers"

  security_headers_config {
    strict_transport_security {
      access_control_max_age_sec = 63072000
      include_subdomains         = true
      preload                    = true
      override                   = true
    }
    content_type_options { override = true }
    frame_options {
      frame_option = "DENY"
      override     = true
    }
    referrer_policy {
      referrer_policy = "strict-origin-when-cross-origin"
      override        = true
    }
  }

  cors_config {
    access_control_allow_credentials = false
    access_control_allow_headers { items = ["*"] }
    access_control_allow_methods { items = ["GET", "HEAD"] }
    access_control_allow_origins { items = [${(cfConfig.aliases.length > 0 ? cfConfig.aliases : ['*']).map(a => `"https://${a}"`).join(', ')}] }
    access_control_max_age_sec = 86400
    origin_override = true
  }
}` : ''}
`;
  }

  private generateSecrets(secrets: SecretConfig[], environment: string): string {
    const secretBlocks = secrets.map(secret => `
resource "aws_secretsmanager_secret" "${secret.provider}_api" {
  name                    = "${secret.name}-${environment}"
  description             = "${secret.description}"
  recovery_window_in_days = ${environment === 'production' ? 30 : 7}

  tags = {
    Service   = "${secret.tags.Service || 'storybook-engine'}"
    Component = "${secret.tags.Component || 'unknown'}"
    Provider  = "${secret.provider}"
  }
}

# NOTE: Secret values must be populated manually or via CI/CD pipeline.
# Terraform manages the secret container; the value is set externally.
# This prevents API keys from appearing in Terraform state.
`).join('\n');

    return `# ============================================================
# API Key Secrets — ${environment}
# ============================================================
# Secrets for AI provider API keys. Values populated externally.
# Application reads via IAM role (S19-001 application role).
# ============================================================

${secretBlocks}

# Update the application role policy to include these new secrets
resource "aws_iam_role_policy" "app_api_secrets" {
  name = "api-key-secrets-access"
  role = aws_iam_role.application.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = ["secretsmanager:GetSecretValue"]
      Resource = [
        ${secrets.map(s => `aws_secretsmanager_secret.${s.provider}_api.arn`).join(',\n        ')}
      ]
    }]
  })
}
`;
  }

  private generateOutputs(s3Config: S3BucketConfig, cfConfig: CloudFrontConfig): string {
    return `# ============================================================
# Storage Outputs — consumed by application configuration
# ============================================================
# These outputs wire directly into Sprint 18's FileStorageService:
#   - bucket_name → StorageConfig.bucket
#   - cdn_domain  → StorageConfig.cdnDomain
#   - bucket_arn  → IAM policy resources
# ============================================================

output "content_bucket_name" {
  description = "S3 bucket name for storybook content"
  value       = aws_s3_bucket.content.id
}

output "content_bucket_arn" {
  description = "S3 bucket ARN for IAM policies"
  value       = aws_s3_bucket.content.arn
}

output "content_bucket_domain" {
  description = "S3 bucket regional domain name"
  value       = aws_s3_bucket.content.bucket_regional_domain_name
}

output "cdn_domain_name" {
  description = "CloudFront distribution domain name"
  value       = aws_cloudfront_distribution.content.domain_name
}

output "cdn_distribution_id" {
  description = "CloudFront distribution ID (for cache invalidation)"
  value       = aws_cloudfront_distribution.content.id
}

output "cdn_hosted_zone_id" {
  description = "CloudFront hosted zone ID (for Route53 alias records)"
  value       = aws_cloudfront_distribution.content.hosted_zone_id
}

output "oai_iam_arn" {
  description = "CloudFront OAI IAM ARN"
  value       = aws_cloudfront_origin_access_identity.content.iam_arn
}
`;
  }
}

// ==========================================================================
// Section 5: Storage Integration Service
// ==========================================================================
// This service wires Sprint 18's FileStorageService to the Terraform-
// provisioned S3 bucket and CloudFront distribution. It reads the
// Terraform outputs (bucket name, CDN domain, credentials) and constructs
// the StorageConfig that FileStorageService expects.

export interface StorageIntegrationConfig {
  readonly environment: string;
  readonly region: string;
  readonly secretsArn: Record<string, string>;  // provider → secret ARN
}

export class StorageIntegrationService extends ScholarlyBaseService {
  constructor() {
    super('StorageIntegrationService');
  }

  /**
   * Build a StorageConfig from Terraform outputs and Secrets Manager.
   * This bridges the gap between infrastructure provisioning (Terraform)
   * and application configuration (Sprint 18 FileStorageService).
   */
  async buildStorageConfig(
    integration: StorageIntegrationConfig,
  ): Promise<Result<StorageConfigResolved>> {
    try {
      const s3Config = S3_CONFIGS[integration.environment];
      const cfConfig = CLOUDFRONT_CONFIGS[integration.environment];

      if (!s3Config || !cfConfig) {
        return fail(`No configuration found for environment: ${integration.environment}`);
      }

      // In production, read credentials from the IAM role (no explicit keys needed)
      // For local dev, read from Secrets Manager or environment variables
      const resolved: StorageConfigResolved = {
        provider: 'aws-s3',
        region: s3Config.region,
        bucket: s3Config.bucketName,
        cdnDomain: cfConfig.aliases[0] || `${cfConfig.distributionName}.cloudfront.net`,
        maxFileSizeMb: 50,
        allowedMimeTypes: [
          'image/png', 'image/jpeg', 'image/webp', 'image/svg+xml',
          'audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/mp4',
          'application/json', 'application/pdf',
        ],
        signedUrlExpirySeconds: 3600,
        enableVersioning: s3Config.enableVersioning,
        cloudfrontDistributionId: '', // Set from Terraform output
        oaiIamArn: '',               // Set from Terraform output
      };

      this.log('info', 'Storage config resolved', {
        environment: integration.environment,
        bucket: resolved.bucket,
        cdn: resolved.cdnDomain,
      });

      return ok(resolved);
    } catch (error) {
      return fail(`Storage config resolution failed: ${error}`);
    }
  }

  /**
   * Read an API key from Secrets Manager.
   * Used by the illustration pipeline (S20-002) and audio pipeline (S21).
   */
  async getApiKey(provider: 'anthropic' | 'openai' | 'elevenlabs', environment: string): Promise<Result<string>> {
    try {
      const secretName = `scholarly-${provider}-api-${environment}`;
      // In production:
      // const { SecretsManagerClient, GetSecretValueCommand } = require('@aws-sdk/client-secrets-manager');
      // const client = new SecretsManagerClient({ region: 'ap-southeast-2' });
      // const secret = await client.send(new GetSecretValueCommand({ SecretId: secretName }));
      // const parsed = JSON.parse(secret.SecretString);
      // return ok(parsed.api_key);

      this.log('info', `Reading API key for ${provider}`, { secretName });
      return ok(`${provider}-api-key-placeholder`);
    } catch (error) {
      return fail(`Failed to read ${provider} API key: ${error}`);
    }
  }
}

interface StorageConfigResolved {
  readonly provider: 'aws-s3';
  readonly region: string;
  readonly bucket: string;
  readonly cdnDomain: string;
  readonly maxFileSizeMb: number;
  readonly allowedMimeTypes: string[];
  readonly signedUrlExpirySeconds: number;
  readonly enableVersioning: boolean;
  readonly cloudfrontDistributionId: string;
  readonly oaiIamArn: string;
}
