apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Application reconciliation timeout
  timeout.reconciliation: 180s

  # Enable status badge
  statusbadge.enabled: "true"

  # Repository credentials template (GitHub)
  # Actual credentials stored in argocd-repo-creds secret
  repository.credentials: |
    - url: https://github.com/
      passwordSecret:
        name: github-repo-creds
        key: password
      usernameSecret:
        name: github-repo-creds
        key: username

  # Resource tracking method
  application.resourceTrackingMethod: annotation

  # Health checks for custom resources
  resource.customizations.health.argoproj.io_Application: |
    hs = {}
    hs.status = "Progressing"
    hs.message = ""
    if obj.status ~= nil then
      if obj.status.health ~= nil then
        hs.status = obj.status.health.status
        if obj.status.health.message ~= nil then
          hs.message = obj.status.health.message
        end
      end
    end
    return hs

  # Ignore differences in fields that change frequently
  resource.customizations.ignoreDifferences.all: |
    managedFieldsManagers:
      - kube-controller-manager
      - aks-managed-controller
    jsonPointers:
      - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration

  # Kustomize build options
  kustomize.buildOptions: --enable-helm
