apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # Default policy for authenticated users
  policy.default: role:readonly

  # RBAC policies
  policy.csv: |
    # Admins can do everything
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, accounts, *, *, allow
    p, role:admin, gpgkeys, *, *, allow
    p, role:admin, logs, *, *, allow
    p, role:admin, exec, *, */*, allow

    # Developers can sync and view applications in their project
    p, role:developer, applications, get, scholarly/*, allow
    p, role:developer, applications, sync, scholarly/*, allow
    p, role:developer, applications, action/*, scholarly/*, allow
    p, role:developer, logs, get, scholarly/*, allow
    p, role:developer, repositories, get, *, allow
    p, role:developer, projects, get, scholarly, allow

    # Viewers can only view
    p, role:viewer, applications, get, */*, allow
    p, role:viewer, projects, get, *, allow
    p, role:viewer, repositories, get, *, allow
    p, role:viewer, logs, get, */*, allow

    # Group bindings (update with your Azure AD groups)
    # g, "azure-ad-group-id", role:admin
    # g, "developers-group-id", role:developer

  # Enable anonymous access for status badges (optional)
  # policy.anonymous.enabled: "true"
