'use client';
/**
 * MathCanvasCASPanel — Priority 2 (CAS Task Interface)
 *
 * This panel is the student-facing side of the CAS assessment engine.
 * It displays a set of tasks generated by Claude (structured, curriculum-
 * aligned) and accepts the student's algebraic answers. Grading is performed
 * ENTIRELY by math.js — no LLM involvement in the marking step.
 *
 * The architecture mirrors the principle established in the phonics BKT system:
 * AI designs the challenge, deterministic algorithms assess the response.
 * Claude is brilliant at creating contextually appropriate tasks at the right
 * difficulty; it is unreliable at marking algebra. math.js is the opposite.
 * Each does what it's best at.
 *
 * UI layout:
 *   ┌─────────────────────────────────────────┐
 *   │ Task progress  [2/4]   ████████░░  50%  │
 *   ├─────────────────────────────────────────┤
 *   │ Task 1 ✓  (collapsed after correct)     │
 *   ├─────────────────────────────────────────┤
 *   │ Task 2 — active                         │
 *   │ "Find ∂f/∂x for this surface"           │
 *   │ ┌──────────────────────────────────┐    │
 *   │ │  ∂f/∂x = [ input field       ]  │    │
 *   │ └──────────────────────────────────┘    │
 *   │  [Submit]  [Hint]                       │
 *   │  ✗ Not correct — try again             │
 *   ├─────────────────────────────────────────┤
 *   │ Task 3  (locked)                        │
 *   │ Task 4  (locked)                        │
 *   └─────────────────────────────────────────┘
 *
 * Tasks unlock sequentially — students must complete task n before seeing n+1.
 * This mirrors the scaffolded approach of phonics phases: you don't jump ahead.
 */

import React, { useState, useRef } from 'react';
import { CheckCircle2, Circle, Lock, ChevronDown, ChevronRight, Lightbulb, Send, RefreshCw, PartyPopper } from 'lucide-react';
import { gradeAnswer, gradeMatrixAnswer } from '@/lib/mathcanvas-cas';
import type { CASTask, CASSessionState } from '@/types/mathcanvas';

const T = {
  bl: '#1e9df1', blLt: '#e3f3fd',
  em: '#10b981', emLt: '#ecfdf5', emMid: '#a7f3d0',
  am: '#f59e0b', amLt: '#fffbeb',
  vl: '#7c3aed', vlLt: '#f5f3ff', vlMid: '#ddd6fe',
  red: '#dc2626', redLt: '#fef2f2',
  ink: '#0f1419', muted: '#6b7280',
  border: '#e5e7eb', surface: '#ffffff',
  bg: '#f8fafc',
} as const;

// =============================================================================
// PROPS
// =============================================================================

export interface CASPanelProps {
  tasks: CASTask[];
  session: CASSessionState;
  introduction: string;
  /** Called when student submits an answer — parent updates session state */
  onSubmitAnswer: (taskId: string, answer: string, result: {
    correct: boolean; marks: number; feedback: string; attemptCount: number;
  }) => void;
  /** Called when the session is complete */
  onComplete: (earnedMarks: number, totalMarks: number) => void;
}

// =============================================================================
// COMPONENT
// =============================================================================

export default function MathCanvasCASPanel({
  tasks,
  session,
  introduction,
  onSubmitAnswer,
  onComplete,
}: CASPanelProps) {
  const [expandedTask, setExpandedTask] = useState<string | null>(tasks[0]?.id ?? null);
  const [showHint, setShowHint] = useState<Record<string, boolean>>({});

  const earnedMarks = Object.values(session.grades).reduce((sum, g) => sum + g.marks, 0);
  const totalMarks = tasks.reduce((sum, t) => sum + t.marks, 0);
  const completedCount = Object.values(session.grades).filter(g => g.correct).length;
  const progressPct = totalMarks > 0 ? Math.round((earnedMarks / totalMarks) * 100) : 0;

  // Which task is the next unanswered one?
  const activeTaskId = tasks.find(t => !session.grades[t.id]?.correct)?.id ?? null;

  const isUnlocked = (task: CASTask, idx: number) => {
    if (idx === 0) return true;
    return session.grades[tasks[idx - 1].id]?.correct === true;
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 12, height: '100%', overflowY: 'auto', padding: '2px 0' }}>

      {/* ── Introduction ── */}
      <div style={{
        padding: '10px 12px', borderRadius: 8,
        background: T.vlLt, border: `1px solid ${T.vlMid}`,
        fontSize: 12, color: T.ink, lineHeight: 1.6,
      }}>
        {introduction}
      </div>

      {/* ── Progress bar ── */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <span style={{ fontSize: 11, fontWeight: 600, color: T.muted }}>
            PROGRESS — {completedCount}/{tasks.length} tasks
          </span>
          <span style={{ fontSize: 12, fontWeight: 700, color: progressPct === 100 ? T.em : T.ink }}>
            {earnedMarks}/{totalMarks} marks
          </span>
        </div>
        <div style={{ height: 6, borderRadius: 3, background: T.border, overflow: 'hidden' }}>
          <div style={{
            height: '100%', borderRadius: 3,
            background: progressPct === 100 ? T.em : T.vl,
            width: `${progressPct}%`,
            transition: 'width 0.4s ease',
          }} />
        </div>
      </div>

      {/* ── Task cards ── */}
      {tasks.map((task, idx) => {
        const grade = session.grades[task.id];
        const unlocked = isUnlocked(task, idx);
        const isActive = task.id === activeTaskId && unlocked;
        const isComplete = grade?.correct === true;
        const isExpanded = expandedTask === task.id;

        return (
          <TaskCard
            key={task.id}
            task={task}
            grade={grade}
            unlocked={unlocked}
            isActive={isActive}
            isComplete={isComplete}
            isExpanded={isExpanded}
            showHint={showHint[task.id] ?? false}
            onToggle={() => setExpandedTask(isExpanded ? null : task.id)}
            onShowHint={() => setShowHint(s => ({ ...s, [task.id]: true }))}
            onSubmit={(answer) => {
              const result = gradeAnswer(task, answer);
              const prevAttempts = session.grades[task.id]?.attemptCount ?? 0;
              onSubmitAnswer(task.id, answer, {
                correct: result.correct,
                marks: result.marks,
                feedback: result.feedback,
                attemptCount: prevAttempts + 1,
              });
              if (result.correct) {
                // Auto-expand next task
                const nextTask = tasks[idx + 1];
                if (nextTask) setExpandedTask(nextTask.id);
                else onComplete(earnedMarks + result.marks, totalMarks);
              }
            }}
          />
        );
      })}

      {/* ── Completion banner ── */}
      {session.completed && (
        <div style={{
          padding: '14px 16px', borderRadius: 10,
          background: T.emLt, border: `1px solid ${T.emMid}`,
          textAlign: 'center',
        }}>
          <div style={{ marginBottom: 4 }}><PartyPopper size={20} style={{ color: T.em }} /></div>
          <div style={{ fontSize: 14, fontWeight: 700, color: T.em }}>
            Session Complete! {earnedMarks}/{totalMarks} marks
          </div>
          <div style={{ fontSize: 12, color: T.ink, marginTop: 4 }}>
            {progressPct === 100 ? 'Perfect score — all tasks correct.' : `${progressPct}% — well done.`}
          </div>
        </div>
      )}
    </div>
  );
}

// =============================================================================
// TASK CARD
// =============================================================================

function TaskCard({
  task, grade, unlocked, isActive, isComplete, isExpanded,
  showHint, onToggle, onShowHint, onSubmit,
}: {
  task: CASTask;
  grade: CASSessionState['grades'][string] | undefined;
  unlocked: boolean;
  isActive: boolean;
  isComplete: boolean;
  isExpanded: boolean;
  showHint: boolean;
  onToggle: () => void;
  onShowHint: () => void;
  onSubmit: (answer: string) => void;
}) {
  const [answer, setAnswer] = useState('');
  const [lastFeedback, setLastFeedback] = useState<string | null>(null);
  const [wasWrong, setWasWrong] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  const handleSubmit = () => {
    if (!answer.trim()) return;
    const result = gradeAnswer(task, answer.trim());
    setLastFeedback(result.feedback);
    setWasWrong(!result.correct);
    onSubmit(answer.trim());
    if (result.correct) setAnswer('');
  };

  const headerBg = isComplete ? T.emLt : isActive ? T.vlLt : T.bg;
  const headerBorder = isComplete ? T.emMid : isActive ? T.vlMid : T.border;

  return (
    <div style={{
      borderRadius: 8,
      border: `1px solid ${headerBorder}`,
      background: headerBg,
      overflow: 'hidden',
      opacity: unlocked ? 1 : 0.55,
      transition: 'opacity 0.2s',
    }}>
      {/* ── Card header ── */}
      <button
        onClick={unlocked ? onToggle : undefined}
        disabled={!unlocked}
        style={{
          width: '100%', display: 'flex', alignItems: 'center', gap: 8,
          padding: '8px 12px', background: 'transparent', border: 'none',
          cursor: unlocked ? 'pointer' : 'default', textAlign: 'left',
        }}
      >
        {/* Status icon */}
        {!unlocked ? (
          <Lock size={13} style={{ color: T.muted, flexShrink: 0 }} />
        ) : isComplete ? (
          <CheckCircle2 size={14} style={{ color: T.em, flexShrink: 0 }} />
        ) : (
          <Circle size={14} style={{ color: isActive ? T.vl : T.muted, flexShrink: 0 }} />
        )}

        {/* Task label */}
        <span style={{ flex: 1, fontSize: 12, fontWeight: 600, color: T.ink }}>
          Task {task.id.split('-').pop() ?? task.id}: {taskTypeLabel(task.type)}
        </span>

        {/* Marks badge */}
        <span style={{
          fontSize: 10, fontWeight: 700,
          padding: '1px 6px', borderRadius: 10,
          background: isComplete ? T.em : T.border,
          color: isComplete ? '#fff' : T.muted,
        }}>
          {grade?.marks ?? 0}/{task.marks}
        </span>

        {/* Expand chevron */}
        {unlocked && (
          isExpanded
            ? <ChevronDown size={12} style={{ color: T.muted }} />
            : <ChevronRight size={12} style={{ color: T.muted }} />
        )}
      </button>

      {/* ── Card body ── */}
      {isExpanded && unlocked && (
        <div style={{ padding: '0 12px 12px', display: 'flex', flexDirection: 'column', gap: 8 }}>

          {/* Task prompt */}
          <div style={{ fontSize: 12, color: T.ink, lineHeight: 1.6 }}>
            {task.prompt}
          </div>

          {/* Expression context — standard algebraic tasks */}
          {!['matrix_multiply','find_determinant','row_reduce','find_eigenvalues'].includes(task.type) && (
            <div style={{
              padding: '6px 10px', borderRadius: 6,
              background: '#f1f5f9', border: `1px solid ${T.border}`,
              fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: T.ink,
            }}>
              f(x,y) = {task.expression}
            </div>
          )}

          {/* Matrix operand display — for matrix task types */}
          {['matrix_multiply','find_determinant','row_reduce','find_eigenvalues'].includes(task.type) && (
            <div style={{ display: 'flex', alignItems: 'center', gap: 16, flexWrap: 'wrap',
              padding: '10px 12px', borderRadius: 8,
              background: '#f8fafc', border: `1px solid ${T.border}` }}>
              {task.matrixA && (
                <MatrixDisplay matrix={task.matrixA} label="A" color={T.bl} />
              )}
              {task.type === 'matrix_multiply' && task.matrixB && (
                <>
                  <span style={{ fontSize: 20, fontWeight: 300, color: T.muted, lineHeight: 1 }}>×</span>
                  <MatrixDisplay matrix={task.matrixB} label="B" color={T.vl} />
                </>
              )}
              {task.type === 'find_determinant' && task.matrixA && (
                <span style={{ fontSize: 12, color: T.muted }}>Find det(A)</span>
              )}
              {task.type === 'row_reduce' && (
                <span style={{ fontSize: 12, color: T.muted }}>Reduce to row echelon form</span>
              )}
              {task.type === 'find_eigenvalues' && (
                <span style={{ fontSize: 12, color: T.muted }}>Find eigenvalues λ of A</span>
              )}
            </div>
          )}

          {!isComplete && (
            <>
              {/* Hint */}
              {task.hint && (
                showHint ? (
                  <div style={{
                    padding: '6px 10px', borderRadius: 6,
                    background: T.amLt, border: `1px solid #fde68a`,
                    fontSize: 11, color: '#92400e',
                  }}>
                    <Lightbulb size={11} style={{ display: 'inline', verticalAlign: 'middle', marginRight: 4 }} />{task.hint}
                  </div>
                ) : (
                  <button
                    onClick={onShowHint}
                    style={{
                      alignSelf: 'flex-start', display: 'flex', alignItems: 'center', gap: 4,
                      padding: '3px 8px', borderRadius: 4, border: `1px solid ${T.am}`,
                      background: T.amLt, cursor: 'pointer', fontSize: 11, color: '#92400e',
                    }}
                  >
                    <Lightbulb size={11} /> Show hint
                  </button>
                )
              )}

              {/* Answer input */}
              <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
                <input
                  ref={inputRef}
                  value={answer}
                  onChange={e => { setAnswer(e.target.value); setLastFeedback(null); }}
                  onKeyDown={e => e.key === 'Enter' && handleSubmit()}
                  placeholder={
                    task.type === 'matrix_multiply' || task.type === 'row_reduce'
                      ? 'Enter result matrix, e.g. [[1,2],[3,4]]'
                      : task.type === 'find_determinant'
                      ? 'Enter determinant, e.g. -2'
                      : task.type === 'find_eigenvalues'
                      ? 'Enter eigenvalues, e.g. 2, -1'
                      : 'Enter your answer…'
                  }
                  style={{
                    flex: 1, padding: '6px 10px',
                    border: `1.5px solid ${wasWrong && lastFeedback ? T.red : isActive ? T.vl : T.border}`,
                    borderRadius: 6, outline: 'none',
                    fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: T.ink,
                    background: T.surface,
                    transition: 'border-color 0.15s',
                  }}
                />
                <button
                  onClick={handleSubmit}
                  disabled={!answer.trim()}
                  style={{
                    padding: '6px 12px', borderRadius: 6,
                    background: answer.trim() ? T.vl : T.border,
                    color: answer.trim() ? '#fff' : T.muted,
                    border: 'none', cursor: answer.trim() ? 'pointer' : 'default',
                    fontSize: 12, fontWeight: 600,
                    display: 'flex', alignItems: 'center', gap: 5,
                    transition: 'background 0.15s',
                  }}
                >
                  <Send size={11} /> Submit
                </button>
              </div>

              {/* Feedback */}
              {lastFeedback && (
                <div style={{
                  fontSize: 11, lineHeight: 1.6, padding: '6px 10px', borderRadius: 6,
                  background: wasWrong ? T.redLt : T.emLt,
                  color: wasWrong ? T.red : T.em,
                  border: `1px solid ${wasWrong ? '#fca5a5' : T.emMid}`,
                }}>
                  {lastFeedback}
                </div>
              )}

              {/* Attempt count */}
              {(grade?.attemptCount ?? 0) > 1 && (
                <div style={{ fontSize: 10, color: T.muted }}>
                  Attempt {grade!.attemptCount}
                </div>
              )}
            </>
          )}

          {/* Completed state — show worked solution */}
          {isComplete && (
            <div style={{
              padding: '8px 10px', borderRadius: 6,
              background: T.emLt, border: `1px solid ${T.emMid}`,
              fontSize: 11, color: '#065f46', lineHeight: 1.6,
            }}>
              <div style={{ fontWeight: 700, marginBottom: 2, display: 'flex', alignItems: 'center', gap: 4 }}><CheckCircle2 size={13} /> Correct</div>
              <div>{task.workedSolution}</div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// =============================================================================
// HELPERS
// =============================================================================

// =============================================================================
// MATRIX DISPLAY — renders number[][] as a styled mathematical matrix
// =============================================================================
//
// A matrix like [[1,2],[3,4]] is displayed with large square brackets,
// aligned columns, and the Scholarly brand token system — no external deps.
// This is the same "no eval, no library" principle as the rest of MathCanvas:
// the JSON array Claude returned is safe to parse; we render it ourselves.

function MatrixDisplay({
  matrix,
  label,
  color = T.bl,
}: {
  matrix: number[][];
  label?: string;
  color?: string;
}) {
  if (!matrix || matrix.length === 0) return null;
  const cols = matrix[0].length;
  // Column width: at least 32px, widen for larger numbers
  const maxVal = Math.max(...matrix.flat().map(v => Math.abs(v)));
  const colW = maxVal >= 100 ? 48 : maxVal >= 10 ? 40 : 32;
  const cellStyle: React.CSSProperties = {
    width: colW, textAlign: 'center', padding: '2px 4px',
    fontFamily: "'JetBrains Mono', monospace", fontSize: 13, color: T.ink,
    lineHeight: 1.8,
  };

  return (
    <div style={{ display: 'inline-flex', flexDirection: 'column', alignItems: 'center', gap: 2 }}>
      {label && (
        <span style={{ fontSize: 11, fontWeight: 700, color, marginBottom: 2 }}>{label}</span>
      )}
      <div style={{ display: 'flex', alignItems: 'center', gap: 0 }}>
        {/* Left bracket */}
        <div style={{
          width: 10, height: matrix.length * 30,
          borderLeft: `2.5px solid ${color}`,
          borderTop: `2px solid ${color}`,
          borderBottom: `2px solid ${color}`,
          borderRadius: '2px 0 0 2px',
        }} />
        {/* Grid */}
        <div style={{ display: 'grid', gridTemplateColumns: `repeat(${cols}, ${colW}px)`, gap: 0 }}>
          {matrix.flat().map((v, i) => (
            <div key={i} style={cellStyle}>{Number.isInteger(v) ? v : v.toFixed(3)}</div>
          ))}
        </div>
        {/* Right bracket */}
        <div style={{
          width: 10, height: matrix.length * 30,
          borderRight: `2.5px solid ${color}`,
          borderTop: `2px solid ${color}`,
          borderBottom: `2px solid ${color}`,
          borderRadius: '0 2px 2px 0',
        }} />
      </div>
    </div>
  );
}

/** Parse JSON matrix string safely */
function tryParseMatrix(s: string): number[][] | null {
  try {
    const cleaned = s.trim().replace(/\s+/g, '');
    const parsed = JSON.parse(cleaned);
    if (!Array.isArray(parsed) || !parsed.every(r => Array.isArray(r))) return null;
    return parsed as number[][];
  } catch { return null; }
}


function taskTypeLabel(type: CASTask['type']): string {
  const labels: Record<CASTask['type'], string> = {
    find_derivative: 'Find the Derivative',
    find_gradient: 'Find the Gradient',
    find_tangent_plane: 'Find the Tangent Plane',
    simplify: 'Simplify',
    expand: 'Expand',
    factorise: 'Factorise',
    evaluate_at_point: 'Evaluate at a Point',
    compare_expressions: 'Are These Equivalent?',
    matrix_multiply: 'Matrix Multiplication',
    find_determinant: 'Find the Determinant',
    row_reduce: 'Row Reduction',
    find_eigenvalues: 'Find the Eigenvalues',
  };
  return labels[type] ?? type;
}

const vlLt = '#f5f3ff';
const vlMid = '#ddd6fe';
const amLt = '#fffbeb';
const redLt = '#fef2f2';
const emMid = '#a7f3d0';
Object.assign(T, { vlLt, vlMid, amLt, redLt, emMid });
